FROM python:3.10

WORKDIR /app

COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api/app.py .
COPY models ./models

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
